Repository peach-hack/auto-matching, pull requests merged in 2018-12, with the labels that each got.

#73 simple_scheduler導入
  Gemfile
  Gemfile.lock
  app/jobs/auto_posting_job.rb
  config/simple_scheduler.yml
Labels: WIP

#108 ユーザ名やパスワードが設定されていない場合はなにもしない
  .env.sample
  app/models/source_site.rb
  db/migrate/20181125134219_create_source_sites.rb
  db/schema.rb
  lib/auto_matching/sender/post_sender_base.rb
Labels: LGTM

#109 Heroku Review App の導入
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: WIP

#117 nuxt2 と typescirpt3 へのアップデート
  .gitignore
  auto-matching-nuxt/components/Card.vue
  auto-matching-nuxt/modules/typescript.js
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/index.vue
  auto-matching-nuxt/store/index.ts
  auto-matching-nuxt/types/index.ts
  auto-matching-nuxt/types/state.ts
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#123 eslint対応
  .gitignore
  auto-matching-nuxt/.eslintignore
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/components/Card.vue
  auto-matching-nuxt/components/Card.vue.d.ts
  auto-matching-nuxt/components/HelloVue.vue
  auto-matching-nuxt/components/HelloVue.vue.d.ts
  auto-matching-nuxt/layouts/default.vue
  auto-matching-nuxt/modules/typescript.js
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/helloworld.vue
  auto-matching-nuxt/pages/index.vue
  auto-matching-nuxt/spec/components/HelloVue.spec.ts
  auto-matching-nuxt/store/.keep
  auto-matching-nuxt/store/index.ts
  auto-matching-nuxt/tsconfig.json
  auto-matching-nuxt/types/index.ts
  auto-matching-nuxt/types/state.ts
  auto-matching-nuxt/yarn.lock
  sideci.yml
Labels: LGTM

#124 Pretter 導入
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/components/HelloVue.vue
  auto-matching-nuxt/components/HelloVue.vue.d.ts
  auto-matching-nuxt/layouts/default.vue
  auto-matching-nuxt/modules/typescript.js
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/index.vue
  auto-matching-nuxt/spec/components/HelloVue.spec.ts
  auto-matching-nuxt/tsconfig.json
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#125 CircleCI 導入
  .circleci/config.yml
  auto-matching-api-rails/Dockerfile
Labels: WIP

#130 RailsとNuxt.js連携のためのプロトタイプ作成(Rails)
  auto-matching-api-rails/.rubocop.yml
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/app/controllers/users/application_controller.rb
  auto-matching-api-rails/app/controllers/users/source_sites_controller.rb
  auto-matching-api-rails/app/views/users/source_sites/_site.json.jbuilder
  auto-matching-api-rails/app/views/users/source_sites/index.json.jbuilder
  auto-matching-api-rails/config/initializers/jbuilder_prettify.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/spec/models/source_site_spec.rb
  auto-matching-api-rails/spec/rails_helper.rb
  auto-matching-api-rails/spec/requests/users/source_sites_spec.rb
  auto-matching-api-rails/spec/support/factory_bot.rb
  auto-matching-api-rails/spec/support/request_helpers.rb
Labels: LGTM

#140 Swagger導入
  auto-matching-api-rails/.gitignore
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/channels/application_cable/channel.rb
  auto-matching-api-rails/app/channels/application_cable/connection.rb
  auto-matching-api-rails/app/controllers/api/application_controller.rb
  auto-matching-api-rails/app/controllers/api/users/source_sites_controller.rb
  auto-matching-api-rails/app/controllers/users/application_controller.rb
  auto-matching-api-rails/app/controllers/users/source_sites_controller.rb
  auto-matching-api-rails/app/helpers/application_helper.rb
  auto-matching-api-rails/app/javascript/app.vue
  auto-matching-api-rails/app/javascript/packs/application.js
  auto-matching-api-rails/app/javascript/packs/hello_vue.js
  auto-matching-api-rails/app/mailers/application_mailer.rb
  auto-matching-api-rails/app/models/source_site.rb
  auto-matching-api-rails/app/serializers/source_site_serializer.rb
  auto-matching-api-rails/app/views/layouts/application.html.erb
  auto-matching-api-rails/app/views/layouts/mailer.html.erb
  auto-matching-api-rails/app/views/layouts/mailer.text.erb
  auto-matching-api-rails/app/views/users/source_sites/_site.json.jbuilder
  auto-matching-api-rails/app/views/users/source_sites/index.json.jbuilder
  auto-matching-api-rails/bin/bundle
  auto-matching-api-rails/bin/rspec
  auto-matching-api-rails/bin/spring
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/spec/requests/users/source_sites_spec.rb
  auto-matching-nuxt/components/HelloVue.vue
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/spec/components/HelloVue.spec.ts
  docker-compose.yml
  swagger.json
  swagger.yaml
Labels: LGTM

#144 プロトタイプ Nuxt.js(GET)
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/config/initializers/cors.rb
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/users/sites/index.vue
  auto-matching-nuxt/yarn.lock
  docker-compose.yml
  swagger.yaml
Labels: LGTM

#150 Nuxt.jsプロジェクトの再構築
  auto-matching-nuxt/.editorconfig
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/.gitignore
  auto-matching-nuxt/.prettierrc
  auto-matching-nuxt/README.md
  auto-matching-nuxt/assets/README.md
  auto-matching-nuxt/assets/css/main.css
  auto-matching-nuxt/components/HelloVue.vue
  auto-matching-nuxt/components/HelloVue.vue.d.ts
  auto-matching-nuxt/components/Logo.vue
  auto-matching-nuxt/components/README.md
  auto-matching-nuxt/layouts/README.md
  auto-matching-nuxt/layouts/default.vue
  auto-matching-nuxt/middleware/README.md
  auto-matching-nuxt/modules/typescript.js
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/README.md
  auto-matching-nuxt/pages/hello.vue
  auto-matching-nuxt/pages/index.vue
  auto-matching-nuxt/pages/users/sites/index.vue
  auto-matching-nuxt/plugins/README.md
  auto-matching-nuxt/spec/components/HelloVue.spec.ts
  auto-matching-nuxt/static/README.md
  auto-matching-nuxt/static/random-data.json
  auto-matching-nuxt/store/.keep
  auto-matching-nuxt/store/README.md
  auto-matching-nuxt/tsconfig.json
  auto-matching-nuxt/types/shims-vue.d.ts
  auto-matching-nuxt/webpack.config.extend.js
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#151 fast_jsonapi導入
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/users/source_sites_controller.rb
  auto-matching-api-rails/app/serializers/source_site_serializer.rb
  auto-matching-api-rails/config/initializers/jbuilder_prettify.rb
  auto-matching-api-rails/spec/requests/users/source_sites_spec.rb
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/users/sites/index.vue
  auto-matching-nuxt/webpack.config.extend.js
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#153 タスクランナー作成
  bin/common.sh
  bin/lint
  bin/lint-fix
  bin/prepush
  bin/test
  tsconfig.json
Labels: LGTM

#155 CoreUI組込
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/assets/scss/_bootstrap-variables.scss
  auto-matching-nuxt/assets/scss/_core-variables.scss
  auto-matching-nuxt/assets/scss/_custom.scss
  auto-matching-nuxt/assets/scss/core/_animate.scss
  auto-matching-nuxt/assets/scss/core/_aside.scss
  auto-matching-nuxt/assets/scss/core/_avatars.scss
  auto-matching-nuxt/assets/scss/core/_badge.scss
  auto-matching-nuxt/assets/scss/core/_breadcrumb-menu.scss
  auto-matching-nuxt/assets/scss/core/_breadcrumb.scss
  auto-matching-nuxt/assets/scss/core/_buttons.scss
  auto-matching-nuxt/assets/scss/core/_callout.scss
  auto-matching-nuxt/assets/scss/core/_card.scss
  auto-matching-nuxt/assets/scss/core/_charts.scss
  auto-matching-nuxt/assets/scss/core/_dropdown-menu-right.scss
  auto-matching-nuxt/assets/scss/core/_dropdown.scss
  auto-matching-nuxt/assets/scss/core/_footer.scss
  auto-matching-nuxt/assets/scss/core/_grid.scss
  auto-matching-nuxt/assets/scss/core/_input-group.scss
  auto-matching-nuxt/assets/scss/core/_layout.scss
  auto-matching-nuxt/assets/scss/core/_loading.scss
  auto-matching-nuxt/assets/scss/core/_mixins.scss
  auto-matching-nuxt/assets/scss/core/_mobile.scss
  auto-matching-nuxt/assets/scss/core/_modal.scss
  auto-matching-nuxt/assets/scss/core/_nav.scss
  auto-matching-nuxt/assets/scss/core/_navbar.scss
  auto-matching-nuxt/assets/scss/core/_others.scss
  auto-matching-nuxt/assets/scss/core/_progress.scss
  auto-matching-nuxt/assets/scss/core/_rtl.scss
  auto-matching-nuxt/assets/scss/core/_sidebar.scss
  auto-matching-nuxt/assets/scss/core/_switches.scss
  auto-matching-nuxt/assets/scss/core/_tables.scss
  auto-matching-nuxt/assets/scss/core/_temp.scss
  auto-matching-nuxt/assets/scss/core/_typography.scss
  auto-matching-nuxt/assets/scss/core/_utilities.scss
  auto-matching-nuxt/assets/scss/core/_variables.scss
  auto-matching-nuxt/assets/scss/core/_widgets.scss
  auto-matching-nuxt/assets/scss/core/core.scss
  auto-matching-nuxt/assets/scss/core/utilities/_background.scss
  auto-matching-nuxt/assets/scss/core/utilities/_borders.scss
  auto-matching-nuxt/assets/scss/core/utilities/_display.scss
  auto-matching-nuxt/assets/scss/style.scss
  auto-matching-nuxt/assets/scss/vendors/_variables.scss
  auto-matching-nuxt/assets/scss/vendors/chart.js/chart.scss
  auto-matching-nuxt/components/Footer.vue
  auto-matching-nuxt/components/_nav.js
  auto-matching-nuxt/components/index.js
  auto-matching-nuxt/layouts/clean.vue
  auto-matching-nuxt/layouts/default.vue
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/index.vue
  auto-matching-nuxt/pages/sourcesites.vue
  auto-matching-nuxt/yarn.lock
  bin/install
Labels: LGTM

#157 StoryBookの導入
  auto-matching-nuxt/.eslintignore
  auto-matching-nuxt/.gitignore
  auto-matching-nuxt/components/Footer.vue
  auto-matching-nuxt/components/MyButton.vue
  auto-matching-nuxt/config/storybook/addons.js
  auto-matching-nuxt/config/storybook/config.js
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/sourcesites.vue
  auto-matching-nuxt/stories/index.stories.js
  auto-matching-nuxt/yarn.lock
Labels: WIP

#165 サイト管理画面作成
  auto-matching-nuxt/assets/scss/core/_variables.scss
  auto-matching-nuxt/components/index.js
  auto-matching-nuxt/components/organisms/Breadcrumb.vue
  auto-matching-nuxt/components/organisms/Footer.vue
  auto-matching-nuxt/layouts/default.vue
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/sourcesites.vue
  auto-matching-nuxt/plugins/i18n-ja.js
  auto-matching-nuxt/plugins/i18n.js
  auto-matching-nuxt/static/logo.png
  auto-matching-nuxt/stories/index.stories.js
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#172 docker-compose整理
  docker-compose-swagger.yml
  docker-compose.yml
Labels: LGTM

#168 サイト管理作成(UPDATE)
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/users/source_sites_controller.rb
  auto-matching-api-rails/app/controllers/application_controller.rb
  auto-matching-api-rails/app/models/source_site.rb
  auto-matching-api-rails/app/serializers/source_site_serializer.rb
  auto-matching-api-rails/config/initializers/rollbar.rb
  auto-matching-api-rails/config/initializers/simple_form.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/db/fixtures/source_site.rb
  auto-matching-api-rails/db/migrate/20181125134219_create_source_sites.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/lib/auto_matching/sender/post_sender_base.rb
  auto-matching-api-rails/spec/factories/source_sites.rb
  auto-matching-api-rails/spec/requests/users/source_sites_spec.rb
  auto-matching-api-rails/yarn.lock
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/components/_nav.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/pages/index.vue
  auto-matching-nuxt/pages/sites/_id.vue
  auto-matching-nuxt/pages/sites/index.vue
  auto-matching-nuxt/pages/sourcesites.vue
  auto-matching-nuxt/plugins/api.js
  auto-matching-nuxt/plugins/i18n-ja.js
  auto-matching-nuxt/plugins/swagger-codegen.js
  auto-matching-nuxt/swagger.json
  auto-matching-nuxt/yarn.lock
  swagger.yaml
Labels: LGTM, WIP

#178 README badgeを派手にする
  README.md
Labels: WIP

#179 Rails DB導入
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
Labels: LGTM

#181 ridgepole移行
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/README.md
  auto-matching-api-rails/bin/update
  auto-matching-api-rails/db/migrate/20181124230258_create_posts.rb
  auto-matching-api-rails/db/migrate/20181125134219_create_source_sites.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/Schemafile
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/db/schemas/source_sites.schema
  auto-matching-api-rails/lib/tasks/db.rake
  auto-matching-api-rails/lib/tasks/ridgepole.rake
  auto-matching-api-rails/spec/rails_helper.rb
Labels: LGTM

#173 サイト管理UI作成(update) part2
  .gitignore
  README.md
  auto-matching-nuxt/pages/sites/_id.vue
  bin/sonar-scanner
Labels: WIP

#187 デプロイサーバの設定(Heroku, Netlify)
  README.md
  auto-matching-api-rails/package.json
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/Procfile
  auto-matching-nuxt/config/environments/env.development.js
  auto-matching-nuxt/config/environments/env.production.js
  auto-matching-nuxt/config/environments/env.staging.js
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/plugins/api.js
  netlify.toml
Labels: WIP

#192 掲示板監視のプロトタイプ
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/db/fixtures/post.rb
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/checker/checker_base.rb
  auto-matching-api-rails/lib/auto_matching/checker/executor.rb
  auto-matching-api-rails/lib/auto_matching/checker/happymail.rb
  auto-matching-api-rails/lib/auto_matching/checker/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/checker/merupara.rb
  auto-matching-api-rails/lib/auto_matching/checker/mint.rb
  auto-matching-api-rails/lib/auto_matching/checker/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/checker/wakuwaku.rb
  auto-matching-api-rails/lib/auto_matching/common/driver_base.rb
  auto-matching-api-rails/lib/auto_matching/common/happymail.rb
  auto-matching-api-rails/lib/auto_matching/common/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/common/merupara.rb
  auto-matching-api-rails/lib/auto_matching/common/mint.rb
  auto-matching-api-rails/lib/auto_matching/common/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/common/wakuwaku.rb
  auto-matching-api-rails/lib/auto_matching/reader/executor.rb
  auto-matching-api-rails/lib/auto_matching/reader/happymail.rb
  auto-matching-api-rails/lib/auto_matching/reader/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/reader/merupara.rb
  auto-matching-api-rails/lib/auto_matching/reader/mint.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/reader/wakuwaku.rb
  auto-matching-api-rails/lib/auto_matching/sender/base.rb
  auto-matching-api-rails/lib/auto_matching/sender/happymail.rb
  auto-matching-api-rails/lib/auto_matching/sender/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/sender/merupara.rb
  auto-matching-api-rails/lib/auto_matching/sender/mint.rb
  auto-matching-api-rails/lib/auto_matching/sender/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/sender/sender_base.rb
  auto-matching-api-rails/lib/auto_matching/sender/wakuwaku.rb
  auto-matching-api-rails/lib/tasks/board_watch.rake
  auto-matching-api-rails/lib/tasks/daily_post.rake
  auto-matching-api-rails/lib/tasks/login_check.rake
Labels: LGTM

#196 アフィリエイト対応
  README.md
  auto-matching-api-rails/app/models/source_site.rb
  auto-matching-api-rails/app/serializers/source_site_serializer.rb
  auto-matching-api-rails/db/fixtures/source_site.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/source_sites.schema
  auto-matching-api-rails/spec/factories/source_sites.rb
  auto-matching-nuxt/pages/sites/index.vue
  swagger.json
  swagger.yaml
Labels: LGTM

#206 pwa対応
  .gitignore
  auto-matching-nuxt/.gitignore
  auto-matching-nuxt/nuxt.config.js
Labels: LGTM

#188 [掲示板監視] DBスキーマとモデルの作成
  auto-matching-api-rails/.gitignore
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/Schemafile
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/db/schemas/profiles.schema
Labels: LGTM

#209 サイト管理画面(PUT)作成
  .circleci/config.yml
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/users/source_sites_controller.rb
  auto-matching-api-rails/app/controllers/application_controller.rb
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/serializers/application_serializer.rb
  auto-matching-api-rails/app/serializers/source_site_serializer.rb
  auto-matching-api-rails/bin/setup
  auto-matching-api-rails/config/initializers/json_param_key_transform.rb
  auto-matching-api-rails/config/initializers/simple_form.rb
  auto-matching-api-rails/db/fixtures/source_site.rb
  auto-matching-api-rails/spec/factories/posts.rb
  auto-matching-api-rails/spec/factories/source_sites.rb
  auto-matching-api-rails/spec/rails_helper.rb
  auto-matching-api-rails/spec/requests/users/source_sites_spec.rb
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/components/organisms/SitesTable.vue
  auto-matching-nuxt/src/pages/sites/_id.vue
  auto-matching-nuxt/src/pages/sites/index.vue
  auto-matching-nuxt/src/store/index.js
  auto-matching-nuxt/src/types/index.d.ts
  auto-matching-nuxt/yarn.lock
  docker-compose.yml
  swagger.yaml
Labels: LGTM
