Repository peach-hack/auto-matching, pull requests merged in 2019-01, with the labels that each got.

#212 SourceSiteからのPost処理
  auto-matching-api-rails/app/controllers/options_request_controller.rb
  auto-matching-api-rails/app/serializers/source_site_serializer.rb
  auto-matching-api-rails/config/initializers/cors.rb
  auto-matching-api-rails/config/initializers/rollbar.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/pages/sites/_id.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/plugins/index.js
  auto-matching-nuxt/src/plugins/swagger-codegen.js
  auto-matching-nuxt/src/store/index.js
  auto-matching-nuxt/tsconfig.json
  auto-matching-nuxt/yarn.lock
  swagger.json
  swagger.yaml
Labels: LGTM

#211 掲示板監視モデル作成
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/models/profile.rb
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/lib/auto_matching/reader/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/reader/merupara.rb
  auto-matching-api-rails/lib/auto_matching/reader/mint.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/spec/factories/profiles.rb
  auto-matching-api-rails/spec/models/profile_spec.rb
Labels: LGTM

#215 Jestでのサイト管理画面テスト
  auto-matching-api-rails/db/schema.rb
  auto-matching-nuxt/.eslintignore
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/spec/store/index.spec.ts
  auto-matching-nuxt/spec/store/sites.spec.ts
  auto-matching-nuxt/src/components/HelloVue.vue
  auto-matching-nuxt/src/components/HelloVue.vue.d.ts
  auto-matching-nuxt/src/components/MyButton.vue
  auto-matching-nuxt/src/components/organisms/SiteForm.vue
  auto-matching-nuxt/src/components/organisms/SitesTable.vue
  auto-matching-nuxt/src/pages/sites/_id.vue
  auto-matching-nuxt/src/pages/sites/index.vue
  auto-matching-nuxt/src/plugins/cookieStorage.js
  auto-matching-nuxt/src/store/index.js
  auto-matching-nuxt/src/store/sites.js
  auto-matching-nuxt/src/stories/.keep
  auto-matching-nuxt/src/stories/index.stories.js
  auto-matching-nuxt/tsconfig.json
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#222 掲示板投稿テンプレートと投稿そのもののモデルを分ける
  auto-matching-api-rails/app/models/post_template.rb
  auto-matching-api-rails/db/fixtures/post_template.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/Schemafile
  auto-matching-api-rails/db/schemas/post_templates.schema
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/lib/auto_matching/sender/executor.rb
  bin/heroku_reset_db.sh
  bin/install.sh
  bin/lint-fix.sh
  bin/lint.sh
  bin/prepush
  bin/prepush.sh
  bin/sonar-scanner.sh
  bin/test.sh
  package.json
Labels: LGTM

#226 vscode 設定の共有
  .gitignore
  .vscode/settings.json
  .vscode/tasks.json
  auto-matching-api-rails/.solargraph.yml
  auto-matching-api-rails/.vscode/settings.json
  auto-matching-api-rails/.vscode/tasks.json
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-nuxt/.vscode/settings.json
  auto-matching-nuxt/.vscode/tasks.json
  auto-matching.code-workspace
Labels: LGTM

#224 PCMAXの不具合調査
  auto-matching-api-rails/lib/auto_matching/common/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/merupara.rb
  auto-matching-api-rails/lib/auto_matching/reader/mint.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/sender/executor.rb
  auto-matching-api-rails/lib/auto_matching/sender/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/sender/wakuwaku.rb
Labels: LGTM

#223 掲示板投稿テンプレート画面
  auto-matching-api-rails/app/controllers/api/users/posts/templates_controller.rb
  auto-matching-api-rails/app/serializers/post_template_serializer.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/db/fixtures/post_template.rb
  auto-matching-api-rails/spec/factories/post_templates.rb
  auto-matching-api-rails/spec/requests/users/posts/templates_spec.rb
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/components/_nav.js
  auto-matching-nuxt/src/pages/posts/auto/index.vue
  auto-matching-nuxt/src/pages/posts/manual/index.vue
  auto-matching-nuxt/src/pages/posts/templates/index.vue
  auto-matching-nuxt/src/plugins/i18n-ja.js
  auto-matching-nuxt/yarn.lock
  auto-matching.code-workspace
Labels: LGTM

#231 BASIC認証
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#227 掲示板投稿テンプレート画面
  .gitignore
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/spec/store/sites.spec.ts
  auto-matching-nuxt/src/components/molecules/SubmitButtonGroup.vue
  auto-matching-nuxt/src/components/organisms/SiteForm.vue
  auto-matching-nuxt/src/components/organisms/SitesTable.vue
  auto-matching-nuxt/src/components/organisms/TemplateForm.vue
  auto-matching-nuxt/src/components/organisms/TemplatesTable.vue
  auto-matching-nuxt/src/pages/posts/templates/_id.vue
  auto-matching-nuxt/src/pages/posts/templates/index.vue
  auto-matching-nuxt/src/pages/sites/_id.vue
  auto-matching-nuxt/src/pages/sites/index.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/plugins/i18n-ja.js
  auto-matching-nuxt/src/plugins/index.js
  auto-matching-nuxt/src/plugins/moment.js
  auto-matching-nuxt/src/store/posts.ts
  auto-matching-nuxt/src/store/sites.js
  auto-matching-nuxt/src/store/sites.ts
  auto-matching-nuxt/src/types/shims-vue.d.ts
  auto-matching-nuxt/src/types/site.d.ts
  auto-matching-nuxt/src/types/template.d.ts
  auto-matching-nuxt/src/types/vue-shims.d.ts
  auto-matching-nuxt/tsconfig.json
  auto-matching-nuxt/yarn.lock
  auto-matching.code-workspace
  bin/test.sh
  package.json
  swagger.json
  swagger.yaml
Labels: LGTM

#234 docker selenium対応
  auto-matching-api-rails/Dockerfile
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/lib/auto_matching/base.rb
Labels: LGTM

#236 log強化
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/checker/checker_base.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/sender/sender_base.rb
Labels: LGTM

#237 一括投稿のテスト
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/common/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/sender/happymail.rb
  auto-matching-api-rails/lib/auto_matching/sender/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/sender/pcmax.rb
  auto-matching-api-rails/tmp/capybara/.keep
  auto-matching-api-rails/tmp/cookie/.keep
  auto-matching-nuxt/package.json
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#238 マニュアル投稿機能(その1)
  auto-matching-api-rails/app/controllers/api/users/posts/manual_posts_controller.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-nuxt/src/components/_nav.js
  auto-matching-nuxt/src/components/organisms/ManualPostTable.vue
  auto-matching-nuxt/src/components/organisms/TemplatesTable.vue
  auto-matching-nuxt/src/pages/posts/manual/index.vue
  auto-matching-nuxt/src/plugins/api.js
  swagger.json
  swagger.yaml
Labels: WIP

#241 マニュアル投稿(その２)
  auto-matching-api-rails/.env.sample
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/users/posts/manual_posts_controller.rb
  auto-matching-api-rails/app/jobs/application_job.rb
  auto-matching-api-rails/app/jobs/auto_post_job.rb
  auto-matching-api-rails/app/jobs/manual_post_job.rb
  auto-matching-api-rails/config/application.rb
  auto-matching-api-rails/config/environments/development.rb
  auto-matching-api-rails/config/initializers/redis.rb
  auto-matching-api-rails/config/initializers/sidekiq.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/config/sidekiq.yml
  auto-matching-api-rails/config/simple_scheduler.yml
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/checker/checker_base.rb
  auto-matching-api-rails/lib/auto_matching/common/driver_base.rb
  auto-matching-api-rails/lib/auto_matching/common/happymail.rb
  auto-matching-api-rails/lib/auto_matching/common/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/common/merupara.rb
  auto-matching-api-rails/lib/auto_matching/common/mint.rb
  auto-matching-api-rails/lib/auto_matching/common/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/common/wakuwaku.rb
  auto-matching-api-rails/lib/auto_matching/multi_logger.rb
  auto-matching-api-rails/lib/auto_matching/reader/executor.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/sender/executor.rb
  auto-matching-api-rails/lib/auto_matching/sender/happymail.rb
  auto-matching-api-rails/lib/auto_matching/sender/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/sender/merupara.rb
  auto-matching-api-rails/lib/auto_matching/sender/mint.rb
  auto-matching-api-rails/lib/auto_matching/sender/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/sender/sender_base.rb
  auto-matching-api-rails/lib/auto_matching/sender/wakuwaku.rb
  auto-matching-api-rails/spec/jobs/manual_post_job_spec.rb
  bin/install.sh
  docker-compose.yml
Labels: WIP

#246 マニュアル投稿（逆通信)
  auto-matching-api-rails/app/channels/manual_post_channel.rb
  auto-matching-api-rails/app/jobs/manual_post_job.rb
  auto-matching-api-rails/config/cable.yml
  auto-matching-api-rails/config/environments/development.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/components/organisms/ManualPostTable.vue
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#216 [掲示板監視]PCMAX対応
  auto-matching-api-rails/.env.sample
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/models/profile.rb
  auto-matching-api-rails/app/models/source_site.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/db/schemas/profiles.schema
  auto-matching-api-rails/db/schemas/source_sites.schema
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/reader/merupara.rb
  auto-matching-api-rails/lib/auto_matching/reader/mint.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/sender/wakuwaku.rb
Labels: LGTM

#251 [検索機能] プロトタイプ作成
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/models/profile.rb
  auto-matching-api-rails/app/models/source_site.rb
  auto-matching-api-rails/app/models/source_site/manual_post_history.rb
  auto-matching-api-rails/app/serializers/post_template_serializer.rb
  auto-matching-api-rails/app/serializers/source_site_serializer.rb
  auto-matching-api-rails/config/application.rb
  auto-matching-api-rails/config/environments/development.rb
  auto-matching-api-rails/db/fixtures/post_template.rb
  auto-matching-api-rails/db/fixtures/source_site.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/db/schemas/profiles.schema
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/tasks/test_datas.rake
  auto-matching-api-rails/spec/factories/posts.rb
  auto-matching-api-rails/spec/factories/profiles.rb
  auto-matching-api-rails/spec/factories/source_sites.rb
  auto-matching-api-rails/spec/models/profile_spec.rb
  auto-matching-api-rails/spec/models/source_site_spec.rb
  package.json
Labels: WIP

#255 [掲示板監視] PCMAX対応 その5(本物）
  auto-matching-api-rails/app/jobs/manual_post_job.rb
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/models/profile.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/value_converter.rb
  auto-matching-api-rails/spec/factories/posts.rb
Labels: LGTM

#253 DB検索機能 プロトタイプ作成(その２）
  .gitignore
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/serializers/post_serializer.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/spec/factories/posts.rb
  auto-matching-nuxt/src/components/_nav.js
  auto-matching-nuxt/src/components/atoms/CreateButton.vue
  auto-matching-nuxt/src/components/atoms/SearchButton.vue
  auto-matching-nuxt/src/components/organisms/DbSearchForm.vue
  auto-matching-nuxt/src/components/organisms/KeywordSearchForm.vue
  auto-matching-nuxt/src/components/organisms/RealtimeSearchForm.vue
  auto-matching-nuxt/src/components/organisms/SearchResultTable.vue
  auto-matching-nuxt/src/pages/search/db.vue
  auto-matching-nuxt/src/pages/search/keyword.vue
  auto-matching-nuxt/src/pages/search/realtime.vue
  auto-matching-nuxt/src/pages/sites/_id.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/plugins/i18n-ja.js
  bin/swagger-yaml2json.sh
  package.json
  swagger.json
  swagger.yaml
  tmp/.keep
Labels: LGTM

#282 掲示板検索プロトタイピング(その3)
  auto-matching-api-rails/app/serializers/post_serializer.rb
  auto-matching-nuxt/src/components/molecules/SearchResultList.vue
  auto-matching-nuxt/src/components/organisms/DbSearchForm.vue
  auto-matching-nuxt/src/components/organisms/KeywordSearchForm.vue
  auto-matching-nuxt/src/components/organisms/RealtimeSearchForm.vue
  auto-matching-nuxt/src/components/organisms/SearchResultTable.vue
  auto-matching-nuxt/src/pages/posts/manual/index.vue
  auto-matching-nuxt/src/pages/sites/index.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/store/search.ts
  auto-matching-nuxt/src/types/post.d.ts
  swagger.json
  swagger.yaml
Labels: LGTM

#299 サブタイトル変更(IDE)
  README.md
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/pages/index.vue
Labels: LGTM

#297 [掲示板監視]PCMAXの記述をワクワクメールの記述に合わせる
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/value_converter.rb
  auto-matching-api-rails/lib/auto_matching/reader/wakuwaku.rb
Labels: LGTM, リファクタリング

#298 DB検索(その4)
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/models/profile.rb
  auto-matching-api-rails/app/serializers/post_serializer.rb
  auto-matching-api-rails/config/environments/development.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/db/schemas/profiles.schema
  auto-matching-api-rails/lib/auto_matching/converter/converter_base.rb
  auto-matching-api-rails/lib/auto_matching/converter/happymail.rb
  auto-matching-api-rails/lib/auto_matching/converter/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/converter/merupara.rb
  auto-matching-api-rails/lib/auto_matching/converter/mint.rb
  auto-matching-api-rails/lib/auto_matching/converter/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/converter/wakuwaku.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/value_converter.rb
  auto-matching-api-rails/lib/auto_matching/reader/wakuwaku.rb
  auto-matching-api-rails/lib/tasks/test_datas.rake
  auto-matching-api-rails/spec/factories/posts.rb
  auto-matching-api-rails/spec/factories/profiles.rb
  auto-matching-api-rails/spec/factories/source_sites.rb
  auto-matching-api-rails/spec/lib/auto_matching/converter/pcmax_spec.rb
  auto-matching-api-rails/spec/models/profile_spec.rb
  auto-matching-api-rails/spec/requests/users/source_sites_spec.rb
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/components/molecules/SearchResultList.vue
  auto-matching-nuxt/src/components/organisms/DbSearchForm.vue
  auto-matching-nuxt/src/components/organisms/SearchResultTable.vue
  auto-matching-nuxt/src/store/search.ts
  auto-matching-nuxt/src/types/post.d.ts
  auto-matching-nuxt/yarn.lock
  bin/install.sh
  bin/swagger-yaml2json.sh
Labels: LGTM

#308 DB検索(その５）
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/spec/factories/posts.rb
  auto-matching-api-rails/spec/factories/profiles.rb
  auto-matching-api-rails/spec/factories/source_sites.rb
  auto-matching-nuxt/src/components/organisms/DbSearchForm.vue
Labels: LGTM

#321 Auth0導入
  app.json
  auto-matching-api-rails/.env.sample
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/users/posts/manual_posts_controller.rb
  auto-matching-api-rails/app/controllers/api/users/posts/templates_controller.rb
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/controllers/api/users/source_sites_controller.rb
  auto-matching-api-rails/app/controllers/application_controller.rb
  auto-matching-api-rails/app/models/user.rb
  auto-matching-api-rails/config/initializers/knock.rb
  auto-matching-api-rails/db/schemas/Schemafile
  auto-matching-api-rails/db/schemas/users.schema
  auto-matching-api-rails/spec/factories/users.rb
  auto-matching-api-rails/spec/models/user_spec.rb
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/pages/callback.vue
  auto-matching-nuxt/src/pages/index.vue
  auto-matching-nuxt/src/pages/login.vue
  auto-matching-nuxt/src/pages/logout.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/plugins/auth0.js
  auto-matching-nuxt/src/plugins/axios.js
  auto-matching-nuxt/src/plugins/i18n-ja.js
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#317 [掲示板監視]イククル対応
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/lib/auto_matching/reader/ikukuru.rb
Labels: LGTM

#332 テストが落ちるエラーの解消
  auto-matching-api-rails/app/controllers/api/users/posts/manual_posts_controller.rb
  auto-matching-api-rails/app/controllers/api/users/posts/templates_controller.rb
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/controllers/api/users/source_sites_controller.rb
  auto-matching-api-rails/config/initializers/knock.rb
  auto-matching-api-rails/db/schema.rb
  auto-matching-api-rails/lib/tasks/db.rake
  auto-matching-api-rails/lib/tasks/ridgepole.rake
  auto-matching-api-rails/spec/rails_helper.rb
Labels: LGTM

#345 リアルタイム検索(その２）
  auto-matching-api-rails/app/channels/manual_post_channel.rb
  auto-matching-api-rails/app/channels/search_channel.rb
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/jobs/application_job.rb
  auto-matching-api-rails/app/jobs/auto_job.rb
  auto-matching-api-rails/app/jobs/auto_post_job.rb
  auto-matching-api-rails/app/jobs/manual_job.rb
  auto-matching-api-rails/app/jobs/manual_post_job.rb
  auto-matching-api-rails/app/jobs/realtime_search_job.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/db/fixtures/source_site.rb
  auto-matching-nuxt/.eslintrc.js
  auto-matching-nuxt/src/components/atoms/CreateButton.vue
  auto-matching-nuxt/src/components/atoms/SearchButton.vue
  auto-matching-nuxt/src/components/molecules/SelectedCheckboxSiteTable.vue
  auto-matching-nuxt/src/components/organisms/DbSearchForm.vue
  auto-matching-nuxt/src/components/organisms/RealtimeSearchForm.vue
  auto-matching-nuxt/src/components/organisms/SitesTable.vue
  auto-matching-nuxt/src/pages/index.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/store/search.ts
  swagger.json
  swagger.yaml
Labels: LGTM

#347 データベース設定
  auto-matching-api-rails/app/controllers/api/users/settings/posts_controller.rb
  auto-matching-api-rails/app/controllers/api/users/settings/source_sites_controller.rb
  auto-matching-api-rails/app/controllers/api/users/source_sites_controller.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-nuxt/src/components/_nav.js
  auto-matching-nuxt/src/components/atoms/ClearDbButton.vue
  auto-matching-nuxt/src/components/mixins/DateUtil.ts
  auto-matching-nuxt/src/components/molecules/DbInfoCalloutGroup.vue
  auto-matching-nuxt/src/components/organisms/SiteForm.vue
  auto-matching-nuxt/src/components/organisms/SitesTable.vue
  auto-matching-nuxt/src/pages/settings/db/index.vue
  auto-matching-nuxt/src/pages/settings/sites/_id.vue
  auto-matching-nuxt/src/pages/settings/sites/index.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/plugins/i18n-ja.js
  auto-matching-nuxt/src/store/sites.ts
  swagger.json
  swagger.yaml
Labels: LGTM

#351 認証機能のオリジナル実装
  auto-matching-api-rails/.env.sample
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/sessions_controller.rb
  auto-matching-api-rails/app/controllers/api/users/posts/templates_controller.rb
  auto-matching-api-rails/app/controllers/api/users_controller.rb
  auto-matching-api-rails/app/controllers/application_controller.rb
  auto-matching-api-rails/app/models/user.rb
  auto-matching-api-rails/app/serializers/user_serializer.rb
  auto-matching-api-rails/config/application.rb
  auto-matching-api-rails/config/initializers/cors.rb
  auto-matching-api-rails/config/initializers/knock.rb
  auto-matching-api-rails/config/initializers/session_store.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/db/schemas/users.schema
  auto-matching-api-rails/spec/factories/users.rb
  auto-matching-api-rails/spec/models/user_spec.rb
  auto-matching-nuxt/nuxt.config.js
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/components/_nav.js
  auto-matching-nuxt/src/pages/index.vue
  auto-matching-nuxt/src/pages/login.vue
  auto-matching-nuxt/src/pages/logout.vue
  auto-matching-nuxt/src/pages/signin.vue
  auto-matching-nuxt/src/pages/signout.vue
  auto-matching-nuxt/src/pages/signup.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/plugins/auth0.js
  auto-matching-nuxt/src/plugins/axios.js
  auto-matching-nuxt/src/plugins/i18n-ja.js
  auto-matching-nuxt/src/store/session.ts
  auto-matching-nuxt/yarn.lock
  docker-compose.yml
  swagger.json
  swagger.yaml
Labels: LGTM
