Repository peach-hack/auto-matching, pull requests merged in 2019-02, with the labels that each got.

#369 定期実行の基盤導入
  .gitignore
  auto-matching-api-rails/app/controllers/api/users/posts/daily_crawl_controller.rb
  auto-matching-api-rails/app/jobs/daily_crawl_job.rb
  auto-matching-api-rails/config/routes.rb
  bin/board_watch/index.js
  bin/board_watch/script.sh
  bin/daily_post/index.js
  bin/daily_post/script.sh
Labels: 動作確認, 機能追加

#383 [掲示板監視] 重複保存対応
  README.md
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/models/profile.rb
  auto-matching-api-rails/db/schemas/posts.schema
  auto-matching-api-rails/lib/auto_matching/reader/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/reader/wakuwaku.rb
  auto-matching-api-rails/spec/models/post_spec.rb
  auto-matching-api-rails/spec/requests/users/settings/source_sites_spec.rb
Labels: LGTM, 機能改善

#385 PCMAX不具合調査
  auto-matching-api-rails/lib/auto_matching/converter/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/converter/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/converter/wakuwaku.rb
  auto-matching-api-rails/spec/lib/auto_matching/converter/pcmax_spec.rb
Labels: バグ, 調べる

#387 プロフィール情報削除
  auto-matching-api-rails/app/controllers/api/users/settings/posts_controller.rb
  auto-matching-nuxt/src/components/molecules/DbInfoCalloutGroup.vue
  auto-matching.code-workspace
Labels: LGTM

#388 ページネーション対応
  auto-matching-api-rails/.rubocop.yml
  auto-matching-api-rails/Dockerfile
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/channels/manual_post_channel.rb
  auto-matching-api-rails/app/channels/search_channel.rb
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/jobs/manual_post_job.rb
  auto-matching-api-rails/app/jobs/realtime_search_job.rb
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/app/models/source_site.rb
  auto-matching-api-rails/config/initializers/sidekiq.rb
  auto-matching-api-rails/db/fixtures/source_site.rb
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/common/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/common/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/common/wakuwaku.rb
  auto-matching-api-rails/lib/auto_matching/converter/converter_base.rb
  auto-matching-api-rails/lib/auto_matching/converter/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/converter/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/converter/wakuwaku.rb
  auto-matching-api-rails/lib/auto_matching/reader/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/reader/wakuwaku.rb
  package.json
Labels: LGTM

#391 [掲示板監視] 神奈川対応
  .DS_Store
  auto-matching-api-rails/app/controllers/api/users/posts/daily_crawl_controller.rb
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/jobs/daily_crawl_job.rb
  auto-matching-api-rails/app/jobs/realtime_search_job.rb
  auto-matching-api-rails/lib/auto_matching/base.rb
  auto-matching-api-rails/lib/auto_matching/capybara_helper.rb
  auto-matching-api-rails/lib/auto_matching/reader/executor.rb
  auto-matching-api-rails/lib/auto_matching/reader/pcmax.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-api-rails/lib/auto_matching/reader/wakuwaku.rb
  auto-matching-nuxt/src/components/organisms/RealtimeSearchForm.vue
Labels: WIP

#402 神奈川対応（その２）
  auto-matching-api-rails/app/controllers/api/users/search_controller.rb
  auto-matching-api-rails/app/jobs/realtime_search_job.rb
  auto-matching-api-rails/app/models/post.rb
  auto-matching-api-rails/lib/auto_matching/reader/executor.rb
  auto-matching-api-rails/lib/auto_matching/reader/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
  auto-matching-nuxt/src/plugins/axios.js
Labels: LGTM

#410 ローディング処理
  auto-matching-nuxt/nuxt.config.ts
  auto-matching-nuxt/package.json
  auto-matching-nuxt/src/layouts/default.vue
  auto-matching-nuxt/src/plugins/axios.js
  auto-matching-nuxt/src/store/common.ts
  auto-matching-nuxt/yarn.lock
Labels: LGTM

#413 Rollbar改善
  auto-matching-api-rails/lib/auto_matching/reader/reader_base.rb
Labels: LGTM

#416 イククルのバグ改善
  auto-matching-api-rails/lib/auto_matching/converter/ikukuru.rb
  auto-matching-api-rails/lib/auto_matching/reader/ikukuru.rb
Labels: LGTM

#452 スマートフォン対応
  auto-matching-nuxt/src/components/organisms/Header.vue
  auto-matching-nuxt/src/layouts/default.vue
Labels: LGTM

#463 Slack連携(その2)
  auto-matching-api-rails/app/controllers/api/users/auto/slack_controller.rb
  auto-matching-api-rails/app/models/profile.rb
  auto-matching-api-rails/app/models/slack_channel.rb
  auto-matching-api-rails/app/models/slack_workspace.rb
  auto-matching-api-rails/app/models/source_site.rb
  auto-matching-api-rails/app/serializers/slack_workspace_serializer.rb
  auto-matching-api-rails/app/serializers/user_serializer.rb
  auto-matching-api-rails/db/schemas/Schemafile
  auto-matching-api-rails/db/schemas/slack_channels.schema
  auto-matching-api-rails/db/schemas/slack_workspaces.schema
  auto-matching-api-rails/lib/auto_matching/slack_utils.rb
  auto-matching-api-rails/spec/models/post_spec.rb
  auto-matching-nuxt/src/components/molecules/SlackControlButtonGroup.vue
  auto-matching-nuxt/src/components/organisms/SlackChannelForm.vue
  auto-matching-nuxt/src/pages/auto/slack/index.vue
Labels: LGTM

#471 Slack連携(その3)
  .circleci/config.yml
  auto-matching-nuxt/Dockerfile
  auto-matching-nuxt/src/components/molecules/SlackControlButtonGroup.vue
  auto-matching-nuxt/src/components/organisms/SlackChannelForm.vue
  auto-matching-nuxt/src/pages/auto/slack/index.vue
  auto-matching-nuxt/src/store/slack.ts
  docker-compose.yml
Labels: LGTM

#418 [掲示板監視]DB容量制限機能を作成
  auto-matching-api-rails/app/controllers/api/users/posts/daily_crawl_controller.rb
  auto-matching-api-rails/lib/auto_matching/capacity_control.rb
Labels: LGTM

#472 定期実行設定
  auto-matching-api-rails/.env.sample
  auto-matching-api-rails/Gemfile
  auto-matching-api-rails/Gemfile.lock
  auto-matching-api-rails/app/controllers/api/users/auto/schedule_controller.rb
  auto-matching-api-rails/app/jobs/post_slack_job.rb
  auto-matching-api-rails/app/models/schedule.rb
  auto-matching-api-rails/app/models/slack_channel.rb
  auto-matching-api-rails/app/serializers/schedule_serializer.rb
  auto-matching-api-rails/config/routes.rb
  auto-matching-api-rails/db/schemas/Schemafile
  auto-matching-api-rails/db/schemas/schedule.schema
  auto-matching-api-rails/db/schemas/slack_channels.schema
  auto-matching-api-rails/lib/auto_matching/client/cloudwatch_utils.rb
  auto-matching-api-rails/lib/auto_matching/client/slack_utils.rb
  auto-matching-api-rails/lib/auto_matching/slack_utils.rb
  auto-matching-nuxt/src/components/_nav.js
  auto-matching-nuxt/src/components/organisms/SchedulerForm.vue
  auto-matching-nuxt/src/pages/auto/schedule/index.vue
  auto-matching-nuxt/src/plugins/api.js
  auto-matching-nuxt/src/plugins/i18n-ja.js
  swagger.json
  swagger.yaml
Labels: LGTM

#488 Docusaurusの導入
  README.md
  auto-matching-docs/.dockerignore
  auto-matching-docs/.gitignore
  auto-matching-docs/Dockerfile
  auto-matching-docs/docker-compose.yml
  auto-matching-docs/docs/doc1.md
  auto-matching-docs/docs/doc2.md
  auto-matching-docs/docs/doc3.md
  auto-matching-docs/docs/exampledoc4.md
  auto-matching-docs/docs/exampledoc5.md
  auto-matching-docs/package.json
  auto-matching-docs/website/.gitignore
  auto-matching-docs/website/README.md
  auto-matching-docs/website/blog/2016-03-11-blog-post.md
  auto-matching-docs/website/blog/2017-04-10-blog-post-two.md
  auto-matching-docs/website/blog/2017-09-25-testing-rss.md
  auto-matching-docs/website/blog/2017-09-26-adding-rss.md
  auto-matching-docs/website/blog/2017-10-24-new-version-1.0.0.md
  auto-matching-docs/website/core/Footer.js
  auto-matching-docs/website/i18n/en.json
  auto-matching-docs/website/package.json
  auto-matching-docs/website/pages/en/help.js
  auto-matching-docs/website/pages/en/index.js
  auto-matching-docs/website/pages/en/users.js
  auto-matching-docs/website/sidebars.json
  auto-matching-docs/website/siteConfig.js
  auto-matching-docs/website/static/css/custom.css
  auto-matching-docs/website/static/img/docusaurus.svg
  auto-matching-docs/website/static/img/favicon.png
  auto-matching-docs/website/static/img/favicon/favicon.ico
  auto-matching-docs/website/static/img/oss_logo.png
  auto-matching-docs/website/yarn.lock
  auto-matching-docs/yarn.lock
  docker-compose.yml
  netlify.toml
Labels: LGTM, ドキュメント

#289 連続投稿防止論理の追加
  auto-matching-api-rails/.env.sample
  auto-matching-api-rails/app/jobs/manual_post_job.rb
Labels: LGTM

#482 [掲示板監視]DB容量制限機能リファクタリング
  auto-matching-api-rails/lib/auto_matching/capacity_control.rb
Labels: LGTM
